### ISSUE TITLE
some problems about ruby

### ISSUE THREAD

**Issue by zhuxiaoyu123** [pyelton/Synteny-based-annotator#2]
When i run your script, the system always notice me "/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- fasta_parser (LoadError)" or "/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- annotaion_finder (LoadError)".  Then i tried to execute "gem install fasta_parser/annotation_finder", but no such item was found. 
Really hope your repsonse.

**Comment by isabelschober** [comment]
Hi,
I'm not the author of the scripts, but I solved this issue like this:

In synteny_finder.091311.rb in lines 3 to 6 and in blast_parser.071411.rb in line 1, add the paths to the scripts that are called. 

I changed synteny_finder.091311.rb lines 3 to 6 to 

> require './fasta_parser' #allows usage of fasta parser 
> require './blast_pusher.071411'
> require './blast_job.051909'
> require './blast_parser.071411'

and blast_parser.071411.rb line 1 to

> require './synteny_stats.071411'

and then call synteny_finder.091311.rb from within the folder all scripts are in. 

If you want to call the script from another folder, you would could add full paths in these lines.
